/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreatorsList200,
  CreatorsListParams,
  PersonSingle
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a list of game creators.
 */
export const creatorsList = (
    params?: CreatorsListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<CreatorsList200>(
      {url: `/creators`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getCreatorsListQueryKey = (params?: CreatorsListParams,) => {
    return [
    `/creators`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getCreatorsListQueryOptions = <TData = Awaited<ReturnType<typeof creatorsList>>, TError = unknown>(params?: CreatorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatorsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creatorsList>>> = ({ signal }) => creatorsList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatorsListQueryResult = NonNullable<Awaited<ReturnType<typeof creatorsList>>>
export type CreatorsListQueryError = unknown


export function useCreatorsList<TData = Awaited<ReturnType<typeof creatorsList>>, TError = unknown>(
 params: undefined |  CreatorsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatorsList>>,
          TError,
          Awaited<ReturnType<typeof creatorsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatorsList<TData = Awaited<ReturnType<typeof creatorsList>>, TError = unknown>(
 params?: CreatorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatorsList>>,
          TError,
          Awaited<ReturnType<typeof creatorsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatorsList<TData = Awaited<ReturnType<typeof creatorsList>>, TError = unknown>(
 params?: CreatorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of game creators.
 */

export function useCreatorsList<TData = Awaited<ReturnType<typeof creatorsList>>, TError = unknown>(
 params?: CreatorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatorsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get details of the creator.
 */
export const creatorsRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<PersonSingle>(
      {url: `/creators/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getCreatorsReadQueryKey = (id?: number,) => {
    return [
    `/creators/${id}`
    ] as const;
    }

    
export const getCreatorsReadQueryOptions = <TData = Awaited<ReturnType<typeof creatorsRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreatorsReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creatorsRead>>> = ({ signal }) => creatorsRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreatorsReadQueryResult = NonNullable<Awaited<ReturnType<typeof creatorsRead>>>
export type CreatorsReadQueryError = unknown


export function useCreatorsRead<TData = Awaited<ReturnType<typeof creatorsRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatorsRead>>,
          TError,
          Awaited<ReturnType<typeof creatorsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatorsRead<TData = Awaited<ReturnType<typeof creatorsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creatorsRead>>,
          TError,
          Awaited<ReturnType<typeof creatorsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreatorsRead<TData = Awaited<ReturnType<typeof creatorsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get details of the creator.
 */

export function useCreatorsRead<TData = Awaited<ReturnType<typeof creatorsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creatorsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreatorsReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




