/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GameSingle,
  GamesAdditionsList200,
  GamesAdditionsListParams,
  GamesDevelopmentTeamList200,
  GamesDevelopmentTeamListParams,
  GamesGameSeriesList200,
  GamesGameSeriesListParams,
  GamesList200,
  GamesListParams,
  GamesParentGamesList200,
  GamesParentGamesListParams,
  GamesScreenshotsList200,
  GamesScreenshotsListParams,
  GamesStoresList200,
  GamesStoresListParams,
  Movie,
  ParentAchievement,
  Reddit,
  Twitch,
  Youtube
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a list of games.
 */
export const gamesList = (
    params?: GamesListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesList200>(
      {url: `/games`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesListQueryKey = (params?: GamesListParams,) => {
    return [
    `/games`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesListQueryOptions = <TData = Awaited<ReturnType<typeof gamesList>>, TError = unknown>(params?: GamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesList>>> = ({ signal }) => gamesList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesList>>>
export type GamesListQueryError = unknown


export function useGamesList<TData = Awaited<ReturnType<typeof gamesList>>, TError = unknown>(
 params: undefined |  GamesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesList>>,
          TError,
          Awaited<ReturnType<typeof gamesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesList<TData = Awaited<ReturnType<typeof gamesList>>, TError = unknown>(
 params?: GamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesList>>,
          TError,
          Awaited<ReturnType<typeof gamesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesList<TData = Awaited<ReturnType<typeof gamesList>>, TError = unknown>(
 params?: GamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of games.
 */

export function useGamesList<TData = Awaited<ReturnType<typeof gamesList>>, TError = unknown>(
 params?: GamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of DLC's for the game, GOTY and other editions, companion apps, etc.
 */
export const gamesAdditionsList = (
    gamePk: string,
    params?: GamesAdditionsListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesAdditionsList200>(
      {url: `/games/${gamePk}/additions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesAdditionsListQueryKey = (gamePk?: string,
    params?: GamesAdditionsListParams,) => {
    return [
    `/games/${gamePk}/additions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesAdditionsListQueryOptions = <TData = Awaited<ReturnType<typeof gamesAdditionsList>>, TError = unknown>(gamePk: string,
    params?: GamesAdditionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesAdditionsListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesAdditionsList>>> = ({ signal }) => gamesAdditionsList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesAdditionsListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesAdditionsList>>>
export type GamesAdditionsListQueryError = unknown


export function useGamesAdditionsList<TData = Awaited<ReturnType<typeof gamesAdditionsList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesAdditionsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesAdditionsList>>,
          TError,
          Awaited<ReturnType<typeof gamesAdditionsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesAdditionsList<TData = Awaited<ReturnType<typeof gamesAdditionsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesAdditionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesAdditionsList>>,
          TError,
          Awaited<ReturnType<typeof gamesAdditionsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesAdditionsList<TData = Awaited<ReturnType<typeof gamesAdditionsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesAdditionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of DLC's for the game, GOTY and other editions, companion apps, etc.
 */

export function useGamesAdditionsList<TData = Awaited<ReturnType<typeof gamesAdditionsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesAdditionsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAdditionsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesAdditionsListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of individual creators that were part of the development team.
 */
export const gamesDevelopmentTeamList = (
    gamePk: string,
    params?: GamesDevelopmentTeamListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesDevelopmentTeamList200>(
      {url: `/games/${gamePk}/development-team`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesDevelopmentTeamListQueryKey = (gamePk?: string,
    params?: GamesDevelopmentTeamListParams,) => {
    return [
    `/games/${gamePk}/development-team`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesDevelopmentTeamListQueryOptions = <TData = Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError = unknown>(gamePk: string,
    params?: GamesDevelopmentTeamListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesDevelopmentTeamListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>> = ({ signal }) => gamesDevelopmentTeamList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesDevelopmentTeamListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>>
export type GamesDevelopmentTeamListQueryError = unknown


export function useGamesDevelopmentTeamList<TData = Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesDevelopmentTeamListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesDevelopmentTeamList>>,
          TError,
          Awaited<ReturnType<typeof gamesDevelopmentTeamList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesDevelopmentTeamList<TData = Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError = unknown>(
 gamePk: string,
    params?: GamesDevelopmentTeamListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesDevelopmentTeamList>>,
          TError,
          Awaited<ReturnType<typeof gamesDevelopmentTeamList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesDevelopmentTeamList<TData = Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError = unknown>(
 gamePk: string,
    params?: GamesDevelopmentTeamListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of individual creators that were part of the development team.
 */

export function useGamesDevelopmentTeamList<TData = Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError = unknown>(
 gamePk: string,
    params?: GamesDevelopmentTeamListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesDevelopmentTeamList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesDevelopmentTeamListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of games that are part of the same series.
 */
export const gamesGameSeriesList = (
    gamePk: string,
    params?: GamesGameSeriesListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesGameSeriesList200>(
      {url: `/games/${gamePk}/game-series`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesGameSeriesListQueryKey = (gamePk?: string,
    params?: GamesGameSeriesListParams,) => {
    return [
    `/games/${gamePk}/game-series`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesGameSeriesListQueryOptions = <TData = Awaited<ReturnType<typeof gamesGameSeriesList>>, TError = unknown>(gamePk: string,
    params?: GamesGameSeriesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesGameSeriesListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesGameSeriesList>>> = ({ signal }) => gamesGameSeriesList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesGameSeriesListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesGameSeriesList>>>
export type GamesGameSeriesListQueryError = unknown


export function useGamesGameSeriesList<TData = Awaited<ReturnType<typeof gamesGameSeriesList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesGameSeriesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesGameSeriesList>>,
          TError,
          Awaited<ReturnType<typeof gamesGameSeriesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesGameSeriesList<TData = Awaited<ReturnType<typeof gamesGameSeriesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesGameSeriesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesGameSeriesList>>,
          TError,
          Awaited<ReturnType<typeof gamesGameSeriesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesGameSeriesList<TData = Awaited<ReturnType<typeof gamesGameSeriesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesGameSeriesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of games that are part of the same series.
 */

export function useGamesGameSeriesList<TData = Awaited<ReturnType<typeof gamesGameSeriesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesGameSeriesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesGameSeriesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesGameSeriesListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of parent games for DLC's and editions.
 */
export const gamesParentGamesList = (
    gamePk: string,
    params?: GamesParentGamesListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesParentGamesList200>(
      {url: `/games/${gamePk}/parent-games`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesParentGamesListQueryKey = (gamePk?: string,
    params?: GamesParentGamesListParams,) => {
    return [
    `/games/${gamePk}/parent-games`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesParentGamesListQueryOptions = <TData = Awaited<ReturnType<typeof gamesParentGamesList>>, TError = unknown>(gamePk: string,
    params?: GamesParentGamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesParentGamesListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesParentGamesList>>> = ({ signal }) => gamesParentGamesList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesParentGamesListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesParentGamesList>>>
export type GamesParentGamesListQueryError = unknown


export function useGamesParentGamesList<TData = Awaited<ReturnType<typeof gamesParentGamesList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesParentGamesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesParentGamesList>>,
          TError,
          Awaited<ReturnType<typeof gamesParentGamesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesParentGamesList<TData = Awaited<ReturnType<typeof gamesParentGamesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesParentGamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesParentGamesList>>,
          TError,
          Awaited<ReturnType<typeof gamesParentGamesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesParentGamesList<TData = Awaited<ReturnType<typeof gamesParentGamesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesParentGamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of parent games for DLC's and editions.
 */

export function useGamesParentGamesList<TData = Awaited<ReturnType<typeof gamesParentGamesList>>, TError = unknown>(
 gamePk: string,
    params?: GamesParentGamesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesParentGamesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesParentGamesListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get screenshots for the game.
 */
export const gamesScreenshotsList = (
    gamePk: string,
    params?: GamesScreenshotsListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesScreenshotsList200>(
      {url: `/games/${gamePk}/screenshots`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesScreenshotsListQueryKey = (gamePk?: string,
    params?: GamesScreenshotsListParams,) => {
    return [
    `/games/${gamePk}/screenshots`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesScreenshotsListQueryOptions = <TData = Awaited<ReturnType<typeof gamesScreenshotsList>>, TError = unknown>(gamePk: string,
    params?: GamesScreenshotsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesScreenshotsListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesScreenshotsList>>> = ({ signal }) => gamesScreenshotsList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesScreenshotsListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesScreenshotsList>>>
export type GamesScreenshotsListQueryError = unknown


export function useGamesScreenshotsList<TData = Awaited<ReturnType<typeof gamesScreenshotsList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesScreenshotsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesScreenshotsList>>,
          TError,
          Awaited<ReturnType<typeof gamesScreenshotsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesScreenshotsList<TData = Awaited<ReturnType<typeof gamesScreenshotsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesScreenshotsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesScreenshotsList>>,
          TError,
          Awaited<ReturnType<typeof gamesScreenshotsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesScreenshotsList<TData = Awaited<ReturnType<typeof gamesScreenshotsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesScreenshotsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get screenshots for the game.
 */

export function useGamesScreenshotsList<TData = Awaited<ReturnType<typeof gamesScreenshotsList>>, TError = unknown>(
 gamePk: string,
    params?: GamesScreenshotsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesScreenshotsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesScreenshotsListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get links to the stores that sell the game.
 */
export const gamesStoresList = (
    gamePk: string,
    params?: GamesStoresListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GamesStoresList200>(
      {url: `/games/${gamePk}/stores`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGamesStoresListQueryKey = (gamePk?: string,
    params?: GamesStoresListParams,) => {
    return [
    `/games/${gamePk}/stores`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGamesStoresListQueryOptions = <TData = Awaited<ReturnType<typeof gamesStoresList>>, TError = unknown>(gamePk: string,
    params?: GamesStoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesStoresListQueryKey(gamePk,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesStoresList>>> = ({ signal }) => gamesStoresList(gamePk,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(gamePk), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesStoresListQueryResult = NonNullable<Awaited<ReturnType<typeof gamesStoresList>>>
export type GamesStoresListQueryError = unknown


export function useGamesStoresList<TData = Awaited<ReturnType<typeof gamesStoresList>>, TError = unknown>(
 gamePk: string,
    params: undefined |  GamesStoresListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesStoresList>>,
          TError,
          Awaited<ReturnType<typeof gamesStoresList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesStoresList<TData = Awaited<ReturnType<typeof gamesStoresList>>, TError = unknown>(
 gamePk: string,
    params?: GamesStoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesStoresList>>,
          TError,
          Awaited<ReturnType<typeof gamesStoresList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesStoresList<TData = Awaited<ReturnType<typeof gamesStoresList>>, TError = unknown>(
 gamePk: string,
    params?: GamesStoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get links to the stores that sell the game.
 */

export function useGamesStoresList<TData = Awaited<ReturnType<typeof gamesStoresList>>, TError = unknown>(
 gamePk: string,
    params?: GamesStoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesStoresList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesStoresListQueryOptions(gamePk,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get details of the game.
 */
export const gamesRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GameSingle>(
      {url: `/games/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}`
    ] as const;
    }

    
export const getGamesReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesRead>>> = ({ signal }) => gamesRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesRead>>>
export type GamesReadQueryError = unknown


export function useGamesRead<TData = Awaited<ReturnType<typeof gamesRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesRead>>,
          TError,
          Awaited<ReturnType<typeof gamesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesRead<TData = Awaited<ReturnType<typeof gamesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesRead>>,
          TError,
          Awaited<ReturnType<typeof gamesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesRead<TData = Awaited<ReturnType<typeof gamesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get details of the game.
 */

export function useGamesRead<TData = Awaited<ReturnType<typeof gamesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of game achievements.
 */
export const gamesAchievementsRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<ParentAchievement>(
      {url: `/games/${id}/achievements`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesAchievementsReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/achievements`
    ] as const;
    }

    
export const getGamesAchievementsReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesAchievementsRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesAchievementsReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesAchievementsRead>>> = ({ signal }) => gamesAchievementsRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesAchievementsReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesAchievementsRead>>>
export type GamesAchievementsReadQueryError = unknown


export function useGamesAchievementsRead<TData = Awaited<ReturnType<typeof gamesAchievementsRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesAchievementsRead>>,
          TError,
          Awaited<ReturnType<typeof gamesAchievementsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesAchievementsRead<TData = Awaited<ReturnType<typeof gamesAchievementsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesAchievementsRead>>,
          TError,
          Awaited<ReturnType<typeof gamesAchievementsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesAchievementsRead<TData = Awaited<ReturnType<typeof gamesAchievementsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of game achievements.
 */

export function useGamesAchievementsRead<TData = Awaited<ReturnType<typeof gamesAchievementsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesAchievementsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesAchievementsReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of game trailers.
 */
export const gamesMoviesRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Movie>(
      {url: `/games/${id}/movies`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesMoviesReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/movies`
    ] as const;
    }

    
export const getGamesMoviesReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesMoviesRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesMoviesReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesMoviesRead>>> = ({ signal }) => gamesMoviesRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesMoviesReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesMoviesRead>>>
export type GamesMoviesReadQueryError = unknown


export function useGamesMoviesRead<TData = Awaited<ReturnType<typeof gamesMoviesRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesMoviesRead>>,
          TError,
          Awaited<ReturnType<typeof gamesMoviesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesMoviesRead<TData = Awaited<ReturnType<typeof gamesMoviesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesMoviesRead>>,
          TError,
          Awaited<ReturnType<typeof gamesMoviesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesMoviesRead<TData = Awaited<ReturnType<typeof gamesMoviesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of game trailers.
 */

export function useGamesMoviesRead<TData = Awaited<ReturnType<typeof gamesMoviesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesMoviesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesMoviesReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of most recent posts from the game's subreddit.
 */
export const gamesRedditRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Reddit>(
      {url: `/games/${id}/reddit`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesRedditReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/reddit`
    ] as const;
    }

    
export const getGamesRedditReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesRedditRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesRedditReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesRedditRead>>> = ({ signal }) => gamesRedditRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesRedditReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesRedditRead>>>
export type GamesRedditReadQueryError = unknown


export function useGamesRedditRead<TData = Awaited<ReturnType<typeof gamesRedditRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesRedditRead>>,
          TError,
          Awaited<ReturnType<typeof gamesRedditRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesRedditRead<TData = Awaited<ReturnType<typeof gamesRedditRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesRedditRead>>,
          TError,
          Awaited<ReturnType<typeof gamesRedditRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesRedditRead<TData = Awaited<ReturnType<typeof gamesRedditRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of most recent posts from the game's subreddit.
 */

export function useGamesRedditRead<TData = Awaited<ReturnType<typeof gamesRedditRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesRedditRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesRedditReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a list of visually similar games, available only for business and enterprise API users.
 */
export const gamesSuggestedRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<GameSingle>(
      {url: `/games/${id}/suggested`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesSuggestedReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/suggested`
    ] as const;
    }

    
export const getGamesSuggestedReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesSuggestedRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesSuggestedReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesSuggestedRead>>> = ({ signal }) => gamesSuggestedRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesSuggestedReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesSuggestedRead>>>
export type GamesSuggestedReadQueryError = unknown


export function useGamesSuggestedRead<TData = Awaited<ReturnType<typeof gamesSuggestedRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesSuggestedRead>>,
          TError,
          Awaited<ReturnType<typeof gamesSuggestedRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesSuggestedRead<TData = Awaited<ReturnType<typeof gamesSuggestedRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesSuggestedRead>>,
          TError,
          Awaited<ReturnType<typeof gamesSuggestedRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesSuggestedRead<TData = Awaited<ReturnType<typeof gamesSuggestedRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of visually similar games, available only for business and enterprise API users.
 */

export function useGamesSuggestedRead<TData = Awaited<ReturnType<typeof gamesSuggestedRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesSuggestedRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesSuggestedReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get streams on Twitch associated with the game, available only for business and enterprise API users.
 */
export const gamesTwitchRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Twitch>(
      {url: `/games/${id}/twitch`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesTwitchReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/twitch`
    ] as const;
    }

    
export const getGamesTwitchReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesTwitchRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesTwitchReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesTwitchRead>>> = ({ signal }) => gamesTwitchRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesTwitchReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesTwitchRead>>>
export type GamesTwitchReadQueryError = unknown


export function useGamesTwitchRead<TData = Awaited<ReturnType<typeof gamesTwitchRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesTwitchRead>>,
          TError,
          Awaited<ReturnType<typeof gamesTwitchRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesTwitchRead<TData = Awaited<ReturnType<typeof gamesTwitchRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesTwitchRead>>,
          TError,
          Awaited<ReturnType<typeof gamesTwitchRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesTwitchRead<TData = Awaited<ReturnType<typeof gamesTwitchRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get streams on Twitch associated with the game, available only for business and enterprise API users.
 */

export function useGamesTwitchRead<TData = Awaited<ReturnType<typeof gamesTwitchRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesTwitchRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesTwitchReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get videos from YouTube associated with the game, available only for business and enterprise API users.
 */
export const gamesYoutubeRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<Youtube>(
      {url: `/games/${id}/youtube`, method: 'GET', signal
    },
      options);
    }
  



export const getGamesYoutubeReadQueryKey = (id?: number,) => {
    return [
    `/games/${id}/youtube`
    ] as const;
    }

    
export const getGamesYoutubeReadQueryOptions = <TData = Awaited<ReturnType<typeof gamesYoutubeRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGamesYoutubeReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof gamesYoutubeRead>>> = ({ signal }) => gamesYoutubeRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GamesYoutubeReadQueryResult = NonNullable<Awaited<ReturnType<typeof gamesYoutubeRead>>>
export type GamesYoutubeReadQueryError = unknown


export function useGamesYoutubeRead<TData = Awaited<ReturnType<typeof gamesYoutubeRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesYoutubeRead>>,
          TError,
          Awaited<ReturnType<typeof gamesYoutubeRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesYoutubeRead<TData = Awaited<ReturnType<typeof gamesYoutubeRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gamesYoutubeRead>>,
          TError,
          Awaited<ReturnType<typeof gamesYoutubeRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGamesYoutubeRead<TData = Awaited<ReturnType<typeof gamesYoutubeRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get videos from YouTube associated with the game, available only for business and enterprise API users.
 */

export function useGamesYoutubeRead<TData = Awaited<ReturnType<typeof gamesYoutubeRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gamesYoutubeRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGamesYoutubeReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




