/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  StoreSingle,
  StoresList200,
  StoresListParams
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a list of video game storefronts.
 */
export const storesList = (
    params?: StoresListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<StoresList200>(
      {url: `/stores`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getStoresListQueryKey = (params?: StoresListParams,) => {
    return [
    `/stores`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getStoresListQueryOptions = <TData = Awaited<ReturnType<typeof storesList>>, TError = unknown>(params?: StoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoresListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storesList>>> = ({ signal }) => storesList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoresListQueryResult = NonNullable<Awaited<ReturnType<typeof storesList>>>
export type StoresListQueryError = unknown


export function useStoresList<TData = Awaited<ReturnType<typeof storesList>>, TError = unknown>(
 params: undefined |  StoresListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storesList>>,
          TError,
          Awaited<ReturnType<typeof storesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoresList<TData = Awaited<ReturnType<typeof storesList>>, TError = unknown>(
 params?: StoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storesList>>,
          TError,
          Awaited<ReturnType<typeof storesList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoresList<TData = Awaited<ReturnType<typeof storesList>>, TError = unknown>(
 params?: StoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of video game storefronts.
 */

export function useStoresList<TData = Awaited<ReturnType<typeof storesList>>, TError = unknown>(
 params?: StoresListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoresListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get details of the store.
 */
export const storesRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<StoreSingle>(
      {url: `/stores/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getStoresReadQueryKey = (id?: number,) => {
    return [
    `/stores/${id}`
    ] as const;
    }

    
export const getStoresReadQueryOptions = <TData = Awaited<ReturnType<typeof storesRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStoresReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof storesRead>>> = ({ signal }) => storesRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StoresReadQueryResult = NonNullable<Awaited<ReturnType<typeof storesRead>>>
export type StoresReadQueryError = unknown


export function useStoresRead<TData = Awaited<ReturnType<typeof storesRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof storesRead>>,
          TError,
          Awaited<ReturnType<typeof storesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoresRead<TData = Awaited<ReturnType<typeof storesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof storesRead>>,
          TError,
          Awaited<ReturnType<typeof storesRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStoresRead<TData = Awaited<ReturnType<typeof storesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get details of the store.
 */

export function useStoresRead<TData = Awaited<ReturnType<typeof storesRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof storesRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStoresReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




