/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */
import type { GamePlatformMetacritic } from './gamePlatformMetacritic';
import type { GameSingleRatings } from './gameSingleRatings';
import type { GameSingleReactions } from './gameSingleReactions';
import type { GameSingleAddedByStatus } from './gameSingleAddedByStatus';
import type { GameSingleEsrbRating } from './gameSingleEsrbRating';
import type { GameSinglePlatformsItem } from './gameSinglePlatformsItem';
import type { Genre } from './genre';
import type { Publisher } from './publisher';

export interface GameSingle {
  readonly id?: number;
  /**
   * @minLength 1
   * @pattern ^[-a-zA-Z0-9_]+$
   */
  readonly slug?: string;
  /** @minLength 1 */
  readonly name?: string;
  /** @minLength 1 */
  readonly name_original?: string;
  /** @minLength 1 */
  readonly description?: string;
  readonly metacritic?: number;
  readonly metacritic_platforms?: readonly GamePlatformMetacritic[];
  readonly released?: string;
  readonly tba?: boolean;
  readonly updated?: string;
  readonly background_image?: string;
  readonly background_image_additional?: string;
  /** @minLength 1 */
  readonly website?: string;
  rating: number;
  readonly rating_top?: number;
  readonly ratings?: GameSingleRatings;
  readonly reactions?: GameSingleReactions;
  readonly added?: number;
  readonly added_by_status?: GameSingleAddedByStatus;
  /** in hours */
  readonly playtime?: number;
  readonly screenshots_count?: number;
  readonly movies_count?: number;
  readonly creators_count?: number;
  readonly achievements_count?: number;
  readonly parent_achievements_count?: string;
  /**
   * For example "https://www.reddit.com/r/uncharted/" or "uncharted"
   * @minLength 1
   */
  readonly reddit_url?: string;
  /** @minLength 1 */
  readonly reddit_name?: string;
  /** @minLength 1 */
  readonly reddit_description?: string;
  /** @minLength 1 */
  readonly reddit_logo?: string;
  readonly reddit_count?: number;
  readonly twitch_count?: string;
  readonly youtube_count?: string;
  readonly reviews_text_count?: string;
  readonly ratings_count?: number;
  readonly suggestions_count?: number;
  readonly alternative_names?: readonly string[];
  /**
   * For example "http://www.metacritic.com/game/playstation-4/the-witcher-3-wild-hunt"
   * @minLength 1
   */
  readonly metacritic_url?: string;
  readonly parents_count?: number;
  readonly additions_count?: number;
  readonly game_series_count?: number;
  /** @nullable */
  esrb_rating?: GameSingleEsrbRating;
  platforms?: GameSinglePlatformsItem[];
  readonly genres?: readonly Genre[];
  readonly publishers?: readonly Publisher[];
}
