/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */

export type GamesListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Number of results to return per page.
 */
page_size?: number;
/**
 * Search query.
 */
search?: string;
/**
 * Disable fuzziness for the search query.
 */
search_precise?: boolean;
/**
 * Mark the search query as exact.
 */
search_exact?: boolean;
/**
 * Filter by parent platforms, for example: `1,2,3`.
 */
parent_platforms?: string;
/**
 * Filter by platforms, for example: `4,5`.
 */
platforms?: string;
/**
 * Filter by stores, for example: `5,6`.
 */
stores?: string;
/**
 * Filter by developers, for example: `1612,18893` or `valve-software,feral-interactive`.
 */
developers?: string;
/**
 * Filter by publishers, for example: `354,20987` or `electronic-arts,microsoft-studios`.
 */
publishers?: string;
/**
 * Filter by genres, for example: `4,51` or `action,indie`.
 */
genres?: string;
/**
 * Filter by tags, for example: `31,7` or `singleplayer,multiplayer`.
 */
tags?: string;
/**
 * Filter by creators, for example: `78,28` or `cris-velasco,mike-morasky`.
 */
creators?: string;
/**
 * Filter by a release date, for example: `2010-01-01,2018-12-31.1960-01-01,1969-12-31`.
 */
dates?: string;
/**
 * Filter by an update date, for example: `2020-12-01,2020-12-31`.
 */
updated?: string;
/**
 * Filter by platforms count, for example: `1`.
 */
platforms_count?: number;
/**
 * Filter by a metacritic rating, for example: `80,100`.
 */
metacritic?: string;
/**
 * Exclude games from a particular collection, for example: `123`.
 */
exclude_collection?: number;
/**
 * Exclude additions.
 */
exclude_additions?: boolean;
/**
 * Exclude games which have additions.
 */
exclude_parents?: boolean;
/**
 * Exclude games which included in a game series.
 */
exclude_game_series?: boolean;
/**
 * Exclude stores, for example: `5,6`.
 */
exclude_stores?: string;
/**
 * Available fields: `name`, `released`, `added`, `created`, `updated`, `rating`, `metacritic`. You can reverse the sort order adding a hyphen, for example: `-released`.
 */
ordering?: string;
};
