/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */

export * from './creatorRolesList200';
export * from './creatorRolesListParams';
export * from './creatorsList200';
export * from './creatorsListParams';
export * from './developer';
export * from './developerSingle';
export * from './developersList200';
export * from './developersListParams';
export * from './game';
export * from './gameAddedByStatus';
export * from './gameEsrbRating';
export * from './gameEsrbRatingName';
export * from './gameEsrbRatingSlug';
export * from './gamePersonList';
export * from './gamePlatformMetacritic';
export * from './gamePlatformsItem';
export * from './gamePlatformsItemPlatform';
export * from './gamePlatformsItemRequirements';
export * from './gameRatings';
export * from './gameSingle';
export * from './gameSingleAddedByStatus';
export * from './gameSingleEsrbRating';
export * from './gameSingleEsrbRatingName';
export * from './gameSingleEsrbRatingSlug';
export * from './gameSinglePlatformsItem';
export * from './gameSinglePlatformsItemPlatform';
export * from './gameSinglePlatformsItemRequirements';
export * from './gameSingleRatings';
export * from './gameSingleReactions';
export * from './gameStoreFull';
export * from './gamesAdditionsList200';
export * from './gamesAdditionsListParams';
export * from './gamesDevelopmentTeamList200';
export * from './gamesDevelopmentTeamListParams';
export * from './gamesGameSeriesList200';
export * from './gamesGameSeriesListParams';
export * from './gamesList200';
export * from './gamesListParams';
export * from './gamesParentGamesList200';
export * from './gamesParentGamesListParams';
export * from './gamesScreenshotsList200';
export * from './gamesScreenshotsListParams';
export * from './gamesStoresList200';
export * from './gamesStoresListParams';
export * from './genre';
export * from './genreSingle';
export * from './genresList200';
export * from './genresListParams';
export * from './movie';
export * from './movieData';
export * from './parentAchievement';
export * from './person';
export * from './personSingle';
export * from './platform';
export * from './platformParentSingle';
export * from './platformSingle';
export * from './platformsList200';
export * from './platformsListParams';
export * from './platformsListsParentsList200';
export * from './platformsListsParentsListParams';
export * from './position';
export * from './publisher';
export * from './publisherSingle';
export * from './publishersList200';
export * from './publishersListParams';
export * from './reddit';
export * from './screenShot';
export * from './store';
export * from './storeSingle';
export * from './storesList200';
export * from './storesListParams';
export * from './tag';
export * from './tagSingle';
export * from './tagsList200';
export * from './tagsListParams';
export * from './twitch';
export * from './youtube';
export * from './youtubeThumbnails';