/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * RAWG Video Games Database API
 * 
The largest open video games database.

### Why build on RAWG
- More than 350,000 games for 50 platforms including mobiles.
- Rich metadata: tags, genres, developers, publishers, individual creators, official websites, release dates,
Metacritic ratings.
- Where to buy: links to digital distribution services
- Similar games based on visual similarity.
- Player activity data: Steam average playtime and RAWG player counts and ratings.
- Actively developing and constantly getting better by user contribution and our algorithms.

### Terms of Use
- Free for personal use as long as you attribute RAWG as the source of the data and/or images and add an active
hyperlink from every page where the data of RAWG is used.
- Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000
page views per month. If your project is larger than that, email us at [api@rawg.io](mailto:api@rawg.io) for
commercial terms.
- No cloning. It would not be cool if you used our API to launch a clone of RAWG. We know it is not always easy
to say what is a duplicate and what isn't. Drop us a line at [api@rawg.io](mailto:api@rawg.io) if you are in doubt,
and we will talk it through.
- You must include an API key with every request. The key can be obtained at https://rawg.io/apidocs.
If you don’t provide it, we may ban your requests.

__[Read more](https://rawg.io/apidocs)__.

 * OpenAPI spec version: v1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PlatformSingle,
  PlatformsList200,
  PlatformsListParams,
  PlatformsListsParentsList200,
  PlatformsListsParentsListParams
} from '.././model';

import { customFetch } from '.././custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get a list of video game platforms.
 */
export const platformsList = (
    params?: PlatformsListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<PlatformsList200>(
      {url: `/platforms`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPlatformsListQueryKey = (params?: PlatformsListParams,) => {
    return [
    `/platforms`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPlatformsListQueryOptions = <TData = Awaited<ReturnType<typeof platformsList>>, TError = unknown>(params?: PlatformsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlatformsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof platformsList>>> = ({ signal }) => platformsList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlatformsListQueryResult = NonNullable<Awaited<ReturnType<typeof platformsList>>>
export type PlatformsListQueryError = unknown


export function usePlatformsList<TData = Awaited<ReturnType<typeof platformsList>>, TError = unknown>(
 params: undefined |  PlatformsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsList>>,
          TError,
          Awaited<ReturnType<typeof platformsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsList<TData = Awaited<ReturnType<typeof platformsList>>, TError = unknown>(
 params?: PlatformsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsList>>,
          TError,
          Awaited<ReturnType<typeof platformsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsList<TData = Awaited<ReturnType<typeof platformsList>>, TError = unknown>(
 params?: PlatformsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of video game platforms.
 */

export function usePlatformsList<TData = Awaited<ReturnType<typeof platformsList>>, TError = unknown>(
 params?: PlatformsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlatformsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * For instance, for PS2 and PS4 the “parent platform” is PlayStation.
 * @summary Get a list of parent platforms.
 */
export const platformsListsParentsList = (
    params?: PlatformsListsParentsListParams,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<PlatformsListsParentsList200>(
      {url: `/platforms/lists/parents`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPlatformsListsParentsListQueryKey = (params?: PlatformsListsParentsListParams,) => {
    return [
    `/platforms/lists/parents`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPlatformsListsParentsListQueryOptions = <TData = Awaited<ReturnType<typeof platformsListsParentsList>>, TError = unknown>(params?: PlatformsListsParentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlatformsListsParentsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof platformsListsParentsList>>> = ({ signal }) => platformsListsParentsList(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlatformsListsParentsListQueryResult = NonNullable<Awaited<ReturnType<typeof platformsListsParentsList>>>
export type PlatformsListsParentsListQueryError = unknown


export function usePlatformsListsParentsList<TData = Awaited<ReturnType<typeof platformsListsParentsList>>, TError = unknown>(
 params: undefined |  PlatformsListsParentsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsListsParentsList>>,
          TError,
          Awaited<ReturnType<typeof platformsListsParentsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsListsParentsList<TData = Awaited<ReturnType<typeof platformsListsParentsList>>, TError = unknown>(
 params?: PlatformsListsParentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsListsParentsList>>,
          TError,
          Awaited<ReturnType<typeof platformsListsParentsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsListsParentsList<TData = Awaited<ReturnType<typeof platformsListsParentsList>>, TError = unknown>(
 params?: PlatformsListsParentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a list of parent platforms.
 */

export function usePlatformsListsParentsList<TData = Awaited<ReturnType<typeof platformsListsParentsList>>, TError = unknown>(
 params?: PlatformsListsParentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsListsParentsList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlatformsListsParentsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get details of the platform.
 */
export const platformsRead = (
    id: number,
 options?: SecondParameter<typeof customFetch>,signal?: AbortSignal
) => {
      
      
      return customFetch<PlatformSingle>(
      {url: `/platforms/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getPlatformsReadQueryKey = (id?: number,) => {
    return [
    `/platforms/${id}`
    ] as const;
    }

    
export const getPlatformsReadQueryOptions = <TData = Awaited<ReturnType<typeof platformsRead>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPlatformsReadQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof platformsRead>>> = ({ signal }) => platformsRead(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PlatformsReadQueryResult = NonNullable<Awaited<ReturnType<typeof platformsRead>>>
export type PlatformsReadQueryError = unknown


export function usePlatformsRead<TData = Awaited<ReturnType<typeof platformsRead>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsRead>>,
          TError,
          Awaited<ReturnType<typeof platformsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsRead<TData = Awaited<ReturnType<typeof platformsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof platformsRead>>,
          TError,
          Awaited<ReturnType<typeof platformsRead>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePlatformsRead<TData = Awaited<ReturnType<typeof platformsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get details of the platform.
 */

export function usePlatformsRead<TData = Awaited<ReturnType<typeof platformsRead>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof platformsRead>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPlatformsReadQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




